(defun desk1 (bk)
    (fetch (list bk '? '?) )
)
(defun desk2 (bk)
    (mapcar #'rest (desk1 bk))
)
(defun description (bk)
    (reduce #'append (desk2 bk))
)
; (load "description.lsp")
; (description 'B2)
