(defun match-element (a b)
    (or (equal a b)
        (equal b '?)
    )
)
; (load "match-element.lsp")
; (match-element '(B2 color red) '(B2 color red))
; (match-element 'B2 '?)
; (match-element 'B1 'B2)